<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>GoldenTicket.Persistence</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GoldenTicket.Domain\GoldenTicket.Domain.csproj" />
    <ProjectReference Include="..\GoldenTicket.Application\GoldenTicket.Application.csproj" />
  </ItemGroup>

</Project>
