<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>GoldenTicket.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GoldenTicket.Domain\GoldenTicket.Domain.csproj" />
  </ItemGroup>

</Project>
